Enumerable testing
Emmyn5600/enumerable_methods pull request #2
Opened 2021-03-30 07:42 UTC by Emmyn5600

## On this branch, we tested all the methods using RSpec.
### The methods are:

#### my_each
#### my_each_with_index
#### my_select
#### my_all?
#### my_any?
#### my_none?
#### my_count
#### my_map
#### my_inject

##### We tested the possible solutions to see if they're working properly.

2021-03-30 09:15 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED ♻️ 🛑

Hello @Emmyn5600 and @leolpaz, I would like to congratulate you on your great performance.👏🏿 Great work trying to implement all the requirements. This was a great effort. However, there are changes to be made kindly check below ⬇️

- [ ] Rubocop flags the error below when run, please fix this.
![rubocop failure](https://user-images.githubusercontent.com/57832450/112963465-b2004600-9147-11eb-96e3-8f8da319dd3d.png)

- [ ] Kindly test for positive and negative scenarios. I have left a comment giving an example of how you can implement this using the my_select method
![image](https://user-images.githubusercontent.com/57832450/112963871-14f1dd00-9148-11eb-97ae-da1eb8eab95f.png)

## Kindly apply the changes requested so that the project can be approved

## NOTE: 
> When you open a pull request and it is marked as invalid, kindly submit the same pull request after you have applied changes that a TSE requests. You should not create a new pull request.

### Feel free to contact me if you have any questions @Elbie-em

HAPPY CODING 💻

2021-03-30 09:15 UTC, Elbie-em commented on spec/enumerable_tests.rb
- [ ] Kindly test positive and negative scenarios, an example, in this case, could be adding a word to your array that has a length greater or less than 6 to create a negative scenario.

2021-03-30 11:56 UTC, Emmyn5600 commented
- We tested the negative scenario for the my_select method as it was requested

- We deleted the Rspec keyword  to correct linter errors shown by rubocop

2021-03-30 13:02 UTC, george-shammar requested changes
**### STATUS: CHANGES REQUIRED** :recycle:

It's a great job you have done there. Your tests are passing. Good job!!! :clap: :clap: :clap:

However, we need to make some changes:

- [ ] Negative text cases are still not been covered. You need to expand the scope of your test to cover negative cases. There should be a spec for the correct usage of the method and also a spec for the wrong usage of the method. E.g positive test case (it "returns all the numbers divisible by 2") E.g negative test case( it "does not return all the numbers divisible by 2"). 

[### **OPTIONAL**]

- [x] Update your README. I couldn't run your tests with `rspec spec/enumerable.rb` as directed in your README but I was able to run it with `rspec spec/enumerable_tests.rb`

Overall, you're doing well. Do not be tired, you're almost there. :muscle: :muscle:

Submit another CRR once you're done.

If you need further clarification, reach me on slack at @George Gbenle

Happy coding. :smiley:

2021-03-31 02:18 UTC, bini-i approved these changes
# Status: Approved :heavy_check_mark:     
### Hello team :wave: 

Thanks for working on the required changes. Congratulations your project is **approved** :tada: 
You can now merge to master and submit the project completion form

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Part-Time TSE)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

2021-03-31 09:08 UTC, merged